import { createContext, useContext, useState, ReactNode } from "react";
import { CardDescription } from "./ui/card";

type Language =
  | "en"
  | "hi"
  | "ta"
  | "te"
  | "bn"
  | "mr"
  | "kn"
  | "ml"
  | "gu"
  | "ur";

const translations = {
  en: {
    dashboard: "Dashboard",
    careers: "Careers",
    courses: "Courses",
    admin: "Admin",
    logout: "Logout",
    welcome: "Welcome back",
    startAssessment: "Start New Assessment",
    exploreCareers: "Explore Career Library",
    readyToExplore: "Ready to explore your future career possibilities?",
    careerLibrary: "Career Library",
    searchPlaceholder: "Search careers or descriptions...",
    allStreams: "All Streams",
    assessmentResults: "Assessment Results",
    personalityProfile: "Your Personality Profile",
    dominantTrait: "Dominant Trait",
    recommendedCareers: "Recommended Careers",
    suggestedCourses: "Suggested Courses",
    startLine: "Start your journey today",
    startDescription: "Our comprehensive RIASEC assessment analyzes your interests and aptitude to match you with careers you'll love. It only takes about 15 minutes!",
    takeAssessment: "Take Assessment",
    searchProgrammes: "Search programmes or branches...",
    searchCareers: "Search careers...",
    searchQuestions: "Search questions...",
    assessmentQuestions: "Assessment Questions",
    manageItemsDescription: "Manage the psychometric questionnaire items.",
    pleaseEnter: "Please enter your details to sign in.",
    logoSheet1: "Discover Your Ideal Career Path",
    logoSheet2: "Take our scientifically-backed RIASEC assessment to uncover your strengths, interests, and the perfect career opportunities waiting for you.",
    logoSheet3: "Join 10,000+ students discovering their future",
    inProgress: "In Progress",
    completedAssessments: "Completed Assessments",
    assessment: "Assessment",
    completed: "Completed",
    viewResults: "View Results",
    noQuestionsFound1: "No questions found for this assessment.",
    resultDescription1: "Your personalized career profile based on RIASEC model",
    resultDescription2: "Visual representation of your interests across 6 dimensions",
    login: "Login",
    register: "Register",
    fullname: "Full Name",
    username: "Username",
    password: "Password",
    confirm: "Confirm",
    fgPassword: "Forgot password",
    classLevel: "Class Level",
    stream: "Stream",
    city: "City",
    createAccount: "Create Account",
    signIn: "Sign In",
    started: "Started",
    resume: "Resume where you left off",
    continue: "Continue",
    finished: "Finished",
    cardDescription: "View your detailed RIASEC analysis and career recommendations based on this assessment.",
    returnToDashboard: "Return to Dashboard",
    programs: "Programmes",
    careerDescription: "Explore 88 academic programmes and 21 career paths across various streams.",
    notFoundDescription: "Have you come to the right place?",
    previous: "Previous",
    nextQuestion: "Next Question",
    completeAssessment: "Complete Assessment",
    noQuestionsFound2: "No questions found matching your filters.",
    CMsoon: "Career management UI coming soon...",
    UMsoon: "User management UI coming soon...",
  },

  hi: {
    dashboard: "डैशबोर्ड",
    careers: "करियर",
    courses: "पाठ्यक्रम",
    admin: "एडमिन",
    logout: "लॉगआउट",
    welcome: "स्वागत है",
    startAssessment: "नया मूल्यांकन शुरू करें",
    exploreCareers: "करियर लाइब्रेरी देखें",
    readyToExplore: "क्या आप अपने भविष्य की करियर संभावनाओं को तलाशने के लिए तैयार हैं?",
    careerLibrary: "करियर लाइब्रेरी",
    searchPlaceholder: "करियर या विवरण खोजें...",
    allStreams: "सभी स्ट्रीम",
    assessmentResults: "मूल्यांकन परिणाम",
    personalityProfile: "आपका व्यक्तित्व प्रोफ़ाइल",
    dominantTrait: "प्रमुख विशेषता",
    recommendedCareers: "अनुशंसित करियर",
    suggestedCourses: "सुझाए गए पाठ्यक्रम",
    startLine: "आज ही अपनी यात्रा शुरू करें",
    startDescription: "हमारा व्यापक RIASEC मूल्यांकन आपकी रुचियों और योग्यताओं का विश्लेषण करके आपको उन करियर विकल्पों से जोड़ता है जिन्हें आप पसंद करेंगे। इसमें केवल 15 मिनट लगते हैं!",
    takeAssessment: "मूल्यांकन करें",
    searchProgrammes: "प्रोग्राम या शाखाएँ खोजें...",
    searchCareers: "करियर खोजें...",
    searchQuestions: "प्रश्न खोजें...",
    assessmentQuestions: "मूल्यांकन प्रश्न",
    manageItemsDescription: "मनोमितीय प्रश्नावली के मदों का प्रबंधन करें।",
    pleaseEnter: "लॉग इन करने के लिए कृपया अपनी जानकारी दर्ज करें।",
    logoSheet1: "अपने आदर्श करियर पथ की खोज करें",
    logoSheet2: "अपनी खूबियों, रुचियों और आपके लिए मौजूद बेहतरीन करियर अवसरों को जानने के लिए हमारे वैज्ञानिक रूप से प्रमाणित RIASEC मूल्यांकन में भाग लें।",
    logoSheet3: "अपने भविष्य की खोज कर रहे 10,000 से अधिक छात्रों से जुड़ें।",
    inProgress: "प्रगति पर है",
    completedAssessments: "पूर्ण मूल्यांकन",
    assessment: "आकलन",
    completed: "पुरा होना।",
    viewResults: "परिणाम दर्शन",
    noQuestionsFound1: "इस मूल्यांकन के लिए कोई प्रश्न नहीं मिले।",
    resultDescription1: "RIASEC मॉडल पर आधारित आपकी व्यक्तिगत कैरियर प्रोफ़ाइल",
    resultDescription2: "6 आयामों में आपकी रुचियों का दृश्य निरूपण",
    login: "लॉगिन",
    register: "रजिस्टर",
    fullname: "पूरा नाम",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    confirm: "पुष्टि करें",
    fgPassword: "पासवर्ड भूल गए",
    classLevel: "कक्षा स्तर",
    stream: "स्ट्रीम",
    city: "शहर",
    createAccount: "खाता बनाएँ",
    signIn: "साइन इन",
    started: "शुरू किया",
    resume: "जहाँ छोड़ा था वहीं से शुरू करें",
    continue: "जारी रखें",
    finished: "पूर्ण",
    cardDescription: "इस मूल्यांकन के आधार पर अपना विस्तृत RIASEC विश्लेषण और करियर सुझाव देखें।",
    returnToDashboard: "डैशबोर्ड पर लौटें",
    programs: "कार्यक्रम",
    careerDescription: "विभिन्न स्ट्रीम में 88 शैक्षणिक कार्यक्रमों और 21 करियर विकल्पों का अन्वेषण करें।",
    notFoundDescription: "क्या आप सही जगह पर आए हैं?",
    previous: "पिछला",
    nextQuestion: "अगला प्रश्न",
    completeAssessment: "मूल्यांकन पूरा करें",
    noQuestionsFound2: "आपके फ़िल्टर से मेल खाते कोई प्रश्न नहीं मिले।",
    CMsoon: "करियर प्रबंधन UI जल्द आ रहा है...",
    UMsoon: "उपयोगकर्ता प्रबंधन UI जल्द आ रहा है...",
  },
  
  ta: {
    dashboard: "டேஷ்போர்டு",
    careers: "தொழில்",
    courses: "படிப்புகள்",
    admin: "நிர்வாகம்",
    logout: "வெளியேறு",
    welcome: "மீண்டும் வருக",
    startAssessment: "புதிய மதிப்பீட்டைத் தொடங்கு",
    exploreCareers: "தொழில் நூலகத்தை ஆராயுங்கள்",
    readyToExplore: "உங்கள் எதிர்கால தொழில் வாய்ப்புகளை ஆராயத் தயாரா?",
    careerLibrary: "தொழில் நூலகம்",
    searchPlaceholder: "தொழில் அல்லது விளக்கங்களைத் தேடுங்கள்...",
    allStreams: "அனைத்து துறைகளும்",
    assessmentResults: "மதிப்பீட்டு முடிவுகள்",
    personalityProfile: "உங்கள் ஆளுமை சுயவிவரம்",
    dominantTrait: "ஆதிக்கப் பண்பு",
    recommendedCareers: "பரிந்துரைக்கப்பட்ட தொழில்கள்",
    suggestedCourses: "பரிந்துரைக்கப்பட்ட படிப்புகள்",
    startLine: "இன்றே உங்கள் பயணத்தைத் தொடங்குங்கள்",
    startDescription: "எங்கள் விரிவான RIASEC மதிப்பீடு, உங்கள் ஆர்வங்களையும், நீங்கள் விரும்பும் தொழில்களுடன் உங்களைப் பொருத்துவதற்கான திறனையும் பகுப்பாய்வு செய்கிறது. இதற்கு சுமார் 15 நிமிடங்கள் மட்டுமே ஆகும்!",
    takeAssessment: "மதிப்பீட்டை எடுத்துக் கொள்ளுங்கள்",
    searchProgrammes: "திட்டங்கள் அல்லது கிளைகளைத் தேடுங்கள்...",
    searchCareers: "தேடுதல் தொழில்...",
    searchQuestions: "கேள்விகளைத் தேடு...",
    assessmentQuestions: "மதிப்பீட்டு கேள்விகள்",
    manageItemsDescription: "சைக்கோமெட்ரிக் கேள்வித்தாள் உருப்படிகளை நிர்வகிக்கவும்.",
    pleaseEnter: "உள்நுழைய உங்கள் விவரங்களை உள்ளிடவும்.",
    logoSheet1: "உங்கள் சிறந்த தொழில் பாதையைக் கண்டறியவும்",
    logoSheet2: "உங்கள் பலம், ஆர்வங்கள் மற்றும் உங்களுக்காகக் காத்திருக்கும் சரியான தொழில் வாய்ப்புகளைக் கண்டறிய எங்கள் அறிவியல் ஆதரவு பெற்ற RIASEC மதிப்பீட்டை எடுத்துக் கொள்ளுங்கள்.",
    logoSheet3: "10,000+ மாணவர்களுடன் சேர்ந்து அவர்களின் எதிர்காலத்தைக் கண்டறியவும்",
    inProgress: "செயல்பாட்டில் உள்ளது",
    completedAssessments: "முடிக்கப்பட்ட மதிப்பீடுகள்",
    assessment: "மதிப்பீடு",
    completed: "முடிக்கப்பட்டது",
    viewResults: "முடிவுகளைக் காண்க",
    noQuestionsFound1: "இந்த மதிப்பீட்டிற்கான கேள்விகள் எதுவும் கிடைக்கவில்லை.",
    resultDescription1: "RIASEC மாதிரியை அடிப்படையாகக் கொண்ட உங்கள் தனிப்பயனாக்கப்பட்ட தொழில் சுயவிவரம்.",
    resultDescription2: "6 பரிமாணங்களில் உங்கள் ஆர்வங்களின் காட்சி பிரதிநிதித்துவம்",
    login: "உள்நுழைவு",
    register: "பதிவு",
    fullname: "முழு பெயர்",
    username: "பயனர் பெயர்",
    password: "கடவுச்சொல்",
    confirm: "உறுதிப்படுத்தவும்",
    fgPassword: "கடவுச்சொல் மறந்துவிட்டீர்களா",
    classLevel: "வகுப்பு நிலை",
    stream: "பிரிவு",
    city: "நகரம்",
    createAccount: "கணக்கை உருவாக்கவும்",
    signIn: "உள்நுழையவும்",
    started: "தொடங்கப்பட்டது",
    resume: "நீங்கள் விட்ட இடத்திலிருந்து தொடரவும்",
    continue: "தொடரவும்",
    finished: "முடிந்தது",
    cardDescription: "இந்த மதிப்பீட்டின் அடிப்படையில் உங்கள் விரிவான RIASEC பகுப்பாய்வு மற்றும் தொழில் பரிந்துரைகளைப் பார்க்கவும்.",
    returnToDashboard: "டாஷ்போர்டிற்கு திரும்பவும்",
    programs: "பாடத்திட்டங்கள்",
    careerDescription: "பல்வேறு பிரிவுகளில் 88 கல்வி பாடத்திட்டங்கள் மற்றும் 21 தொழில் பாதைகளை ஆராயுங்கள்.",
    notFoundDescription: "நீங்கள் சரியான இடத்திற்கா வந்துள்ளீர்கள்?",
    previous: "முந்தையது",
    nextQuestion: "அடுத்த கேள்வி",
    completeAssessment: "மதிப்பீட்டை முடிக்கவும்",
    noQuestionsFound2: "உங்கள் வடிப்பான்களுக்கு பொருந்தும் கேள்விகள் எதுவும் இல்லை.",
    CMsoon: "தொழில் மேலாண்மை UI விரைவில் வருகிறது...",
    UMsoon: "பயனர் மேலாண்மை UI விரைவில் வருகிறது...",
  },

  te: {
    dashboard: "డ్యాష్‌బోర్డ్",
    careers: "కెరీర్లు",
    courses: "కోర్సులు",
    admin: "అడ్మిన్",
    logout: "లాగ్ అవుట్",
    welcome: "మళ్ళీ స్వాగతం",
    startAssessment: "కొత్త అసెస్‌మెంట్ ప్రారంభించండి",
    exploreCareers: "కెరీర్ లైబ్రరీని అన్వేషించండి",
    readyToExplore: "మీ భవిష్యత్తు కెరీర్ అవకాశాలను అన్వేషించడానికి సిద్ధంగా ఉన్నారా?",
    careerLibrary: "కెరీర్ లైబ్రరీ",
    searchPlaceholder: "కెరీర్లు లేదా వివరణల కోసం వెతకండి...",
    allStreams: "అన్ని స్ట్రీమ్‌లు",
    assessmentResults: "అసెస్‌మెంట్ ఫలితాలు",
    personalityProfile: "మీ వ్యక్తిత్వ ప్రొఫైల్",
    dominantTrait: "ప్రధాన లక్షణం",
    recommendedCareers: "సిఫార్సు చేయబడిన కెరీర్లు",
    suggestedCourses: "సిఫార్సు చేయబడిన కోర్సులు",
    startLine: "ఈరోజే మీ ప్రయాణాన్ని ప్రారంభించండి",
    startDescription: "మా సమగ్ర RIASEC మూల్యాంకనం మీ ఆసక్తులు మరియు మీరు ఇష్టపడే కెరీర్‌లతో సరిపోల్చడానికి ఉన్న సామర్థ్యాన్ని విశ్లేషిస్తుంది. దీనికి కేవలం 15 నిమిషాలు మాత్రమే పడుతుంది!",
    takeAssessment: "అసెస్‌మెంట్ తీసుకోండి",
    searchProgrammes: "కార్యక్రమాలు లేదా శాఖలను శోధించండి...",
    searchCareers: "కెరీర్‌లను శోధించండి...",
    searchQuestions: "ప్రశ్నలను వెతకండి...",
    assessmentQuestions: "మూల్యాంకన ప్రశ్నలు",
    manageItemsDescription: "సైకోమెట్రిక్ ప్రశ్నాపత్ర అంశాలను నిర్వహించండి.",
    pleaseEnter: "సైన్ ఇన్ చేయడానికి దయచేసి మీ వివరాలను నమోదు చేయండి.",
    logoSheet1: "మీ ఆదర్శ కెరీర్ మార్గాన్ని కనుగొనండి",
    logoSheet2: "మీ బలాలు, ఆసక్తులు మరియు మీ కోసం వేచి ఉన్న పరిపూర్ణ కెరీర్ అవకాశాలను వెలికితీసేందుకు మా శాస్త్రీయంగా మద్దతు ఇవ్వబడిన RIASEC అంచనాను తీసుకోండి.",
    logoSheet3: "10,000+ మంది విద్యార్థులతో కలిసి వారి భవిష్యత్తును కనుగొనండి",
    inProgress: "పురోగతిలో ఉంది",
    completedAssessments: "పూర్తి చేసిన అంచనాలు",
    assessment: "మూల్యాంకనం",
    completed: "పూర్తయింది",
    viewResults: "ఫలితాలను వీక్షించండి",
    noQuestionsFound1: "ఈ అంచనా కోసం ప్రశ్నలు ఏవీ కనుగొనబడలేదు.",
    resultDescription1: "RIASEC మోడల్ ఆధారంగా మీ వ్యక్తిగతీకరించిన కెరీర్ ప్రొఫైల్",
    resultDescription2: "6 కోణాలలో మీ ఆసక్తుల దృశ్య ప్రాతినిధ్యం",
    login: "లాగిన్",
    register: "నమోదు",
    fullname: "పూర్తి పేరు",
    username: "వినియోగదారు పేరు",
    password: "పాస్‌వర్డ్",
    confirm: "నిర్ధారించండి",
    fgPassword: "పాస్‌వర్డ్ మర్చిపోయారా",
    classLevel: "తరగతి స్థాయి",
    stream: "స్ట్రీమ్",
    city: "నగరం",
    createAccount: "ఖాతా సృష్టించండి",
    signIn: "సైన్ ఇన్",
    started: "ప్రారంభించబడింది",
    resume: "మీరు ఆపిన చోట నుండి కొనసాగించండి",
    continue: "కొనసాగించండి",
    finished: "పూర్తైంది",
    cardDescription: "ఈ అంచనాపై ఆధారపడి మీ వివరమైన RIASEC విశ్లేషణ మరియు వృత్తి సూచనలను చూడండి.",
    returnToDashboard: "డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి",
    programs: "కార్యక్రమాలు",
    careerDescription: "వివిధ స్ట్రీమ్‌లలో 88 విద్యా కార్యక్రమాలు మరియు 21 వృత్తి మార్గాలను అన్వేషించండి.",
    notFoundDescription: "మీరు సరైన స్థలానికి వచ్చారా?",
    previous: "మునుపటి",
    nextQuestion: "తదుపరి ప్రశ్న",
    completeAssessment: "అంచనాను పూర్తి చేయండి",
    noQuestionsFound2: "మీ ఫిల్టర్లకు సరిపడే ప్రశ్నలు కనబడలేదు.",
    CMsoon: "కెరీర్ మేనేజ్‌మెంట్ UI త్వరలో వస్తుంది...",
    UMsoon: "యూజర్ మేనేజ్‌మెంట్ UI త్వరలో వస్తుంది...",
  },

  bn: {
    dashboard: "ড্যাশবোর্ড",
    careers: "ক্যারিয়ার",
    courses: "কোর্স",
    admin: "অ্যাডমিন",
    logout: "লগআউট",
    welcome: "স্বাগত",
    startAssessment: "নতুন মূল্যায়ন শুরু করুন",
    exploreCareers: "ক্যারিয়ার লাইব্রেরি অন্বেষণ করুন",
    readyToExplore: "আপনার ভবিষ্যতের ক্যারিয়ারের সম্ভাবনা অন্বেষণ করতে প্রস্তুত?",
    careerLibrary: "ক্যারিয়ার লাইব্রেরি",
    searchPlaceholder: "ক্যারিয়ার বা বিবরণ খুঁজুন...",
    allStreams: "সমস্ত বিভাগ",
    assessmentResults: "মূল্যায়নের ফলাফল",
    personalityProfile: "আপনার ব্যক্তিত্ব প্রোফাইল",
    dominantTrait: "প্রধান বৈশিষ্ট্য",
    recommendedCareers: "প্রস্তাবিত ক্যারিয়ার",
    suggestedCourses: "প্রস্তাবিত কোর্স",
    startLine: "আজই আপনার যাত্রা শুরু করুন",
    startDescription: "আমাদের বিস্তৃত RIASEC মূল্যায়ন আপনার আগ্রহ ও দক্ষতা বিশ্লেষণ করে এমন ক্যারিয়ারের সাথে আপনাকে মিলিয়ে দেয় যা আপনি ভালোবাসবেন। এতে মাত্র প্রায় ১৫ মিনিট সময় লাগে!",
    takeAssessment: "মূল্যায়ন নিন",
    searchProgrammes: "প্রোগ্রাম বা শাখা অনুসন্ধান করুন...",
    searchCareers: "ক্যারিয়ার অনুসন্ধান করুন...",
    searchQuestions: "প্রশ্ন অনুসন্ধান করুন...",
    assessmentQuestions: "মূল্যায়ন প্রশ্নসমূহ",
    manageItemsDescription: "সাইকোমেট্রিক প্রশ্নাবলীর আইটেমগুলো পরিচালনা করুন।",
    pleaseEnter: "সাইন ইন করতে অনুগ্রহ করে আপনার তথ্য প্রদান করুন।",
    logoSheet1: "আপনার আদর্শ ক্যারিয়ার পথ আবিষ্কার করুন",
    logoSheet2: "বৈজ্ঞানিকভাবে প্রমাণিত আমাদের RIASEC মূল্যায়ন গ্রহণ করে আপনার শক্তি, আগ্রহ এবং আপনার জন্য অপেক্ষমান উপযুক্ত ক্যারিয়ার সুযোগগুলো আবিষ্কার করুন।",
    logoSheet3: "10,000+ শিক্ষার্থীর সঙ্গে যুক্ত হন যারা তাদের ভবিষ্যৎ আবিষ্কার করছে",
    inProgress: "চলমান",
    completedAssessments: "সম্পন্ন মূল্যায়নসমূহ",
    assessment: "মূল্যায়ন",
    completed: "সম্পন্ন",
    viewResults: "ফলাফল দেখুন",
    noQuestionsFound1: "এই মূল্যায়নের জন্য কোনো প্রশ্ন পাওয়া যায়নি।",
    resultDescription1: "RIASEC মডেলের উপর ভিত্তি করে আপনার ব্যক্তিগতকৃত ক্যারিয়ার প্রোফাইল",
    resultDescription2: "৬ মাত্রায় আপনার আগ্রহের একটি দৃশ্যমান উপস্থাপনা",
    login: "লগইন",
    register: "নিবন্ধন",
    fullname: "পূর্ণ নাম",
    username: "ব্যবহারকারীর নাম",
    password: "পাসওয়ার্ড",
    confirm: "নিশ্চিত করুন",
    fgPassword: "পাসওয়ার্ড ভুলে গেছেন",
    classLevel: "শ্রেণির স্তর",
    stream: "স্ট্রিম",
    city: "শহর",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    signIn: "সাইন ইন",
    started: "শুরু হয়েছে",
    resume: "যেখান থেকে ছেড়েছিলেন সেখান থেকে শুরু করুন",
    continue: "চালিয়ে যান",
    finished: "সম্পন্ন",
    cardDescription: "এই মূল্যায়নের ভিত্তিতে আপনার বিস্তারিত RIASEC বিশ্লেষণ এবং ক্যারিয়ার সুপারিশ দেখুন।",
    returnToDashboard: "ড্যাশবোর্ডে ফিরে যান",
    programs: "প্রোগ্রামসমূহ",
    careerDescription: "বিভিন্ন স্ট্রিমে ৮৮টি শিক্ষামূলক প্রোগ্রাম এবং ২১টি ক্যারিয়ার পথ অন্বেষণ করুন।",
    notFoundDescription: "আপনি কি সঠিক জায়গায় এসেছেন?",
    previous: "পূর্ববর্তী",
    nextQuestion: "পরবর্তী প্রশ্ন",
    completeAssessment: "মূল্যায়ন সম্পন্ন করুন",
    noQuestionsFound2: "আপনার ফিল্টারের সাথে মিল থাকা কোনো প্রশ্ন পাওয়া যায়নি।",
    CMsoon: "ক্যারিয়ার ম্যানেজমেন্ট UI শীঘ্রই আসছে...",
    UMsoon: "ইউজার ম্যানেজমেন্ট UI শীঘ্রই আসছে...",
  },

  mr: {
    dashboard: "डॅशबोर्ड",
    careers: "करिअर",
    courses: "अभ्यासक्रम",
    admin: "अ‍ॅडमिन",
    logout: "लॉगआउट",
    welcome: "स्वागत आहे",
    startAssessment: "नवीन मूल्यांकन सुरू करा",
    exploreCareers: "करिअर लायब्ररी एक्सप्लोर करा",
    readyToExplore: "तुमच्या भविष्यातील करिअरच्या संधी शोधण्यासाठी तयार आहात?",
    careerLibrary: "करिअर लायब्ररी",
    searchPlaceholder: "करिअर किंवा वर्णन शोधा...",
    allStreams: "सर्व शाखा",
    assessmentResults: "मूल्यांकन निकाल",
    personalityProfile: "तुमचे व्यक्तिमत्व प्रोफाइल",
    dominantTrait: "प्रमुख गुणधर्म",
    recommendedCareers: "शिफारस केलेले करिअर",
    suggestedCourses: "सुचवलेले अभ्यासक्रम",
    startLine: "आजच तुमचा प्रवास सुरू करा",
    startDescription: "आमचे सर्वसमावेशक RIASEC मूल्यमापन तुमच्या आवडी आणि क्षमतेचे विश्लेषण करून तुम्हाला आवडणाऱ्या करिअरशी जुळवते. यासाठी फक्त सुमारे १५ मिनिटे लागतात!",
    takeAssessment: "मूल्यमापन घ्या",
    searchProgrammes: "कार्यक्रम किंवा शाखा शोधा...",
    searchCareers: "करिअर शोधा...",
    searchQuestions: "प्रश्न शोधा...",
    assessmentQuestions: "मूल्यमापन प्रश्न",
    manageItemsDescription: "सायकोमेट्रिक प्रश्नावलीतील घटक व्यवस्थापित करा.",
    pleaseEnter: "साइन इन करण्यासाठी कृपया तुमची माहिती भरा.",
    logoSheet1: "तुमचा आदर्श करिअर मार्ग शोधा",
    logoSheet2: "वैज्ञानिकदृष्ट्या प्रमाणित आमचे RIASEC मूल्यमापन घ्या आणि तुमची ताकद, आवडी व तुमच्यासाठी उपलब्ध असलेल्या योग्य करिअर संधी शोधा.",
    logoSheet3: "तुमचे भविष्य शोधणाऱ्या 10,000+ विद्यार्थ्यांमध्ये सामील व्हा",
    inProgress: "प्रगतीपथावर",
    completedAssessments: "पूर्ण झालेली मूल्यमापन",
    assessment: "मूल्यमापन",
    completed: "पूर्ण",
    viewResults: "निकाल पहा",
    noQuestionsFound1: "या मूल्यमापनासाठी कोणतेही प्रश्न आढळले नाहीत.",
    resultDescription1: "RIASEC मॉडेलवर आधारित तुमची वैयक्तिकृत करिअर प्रोफाइल",
    resultDescription2: "६ परिमाणांमधील तुमच्या आवडींचे दृश्यात्मक सादरीकरण",
    login: "लॉगिन",
    register: "नोंदणी",
    fullname: "पूर्ण नाव",
    username: "वापरकर्तानाव",
    password: "पासवर्ड",
    confirm: "पुष्टी करा",
    fgPassword: "पासवर्ड विसरलात",
    classLevel: "इयत्ता स्तर",
    stream: "शाखा",
    city: "शहर",
    createAccount: "खाते तयार करा",
    signIn: "साइन इन",
    started: "सुरू केले",
    resume: "जिथे थांबलात तिथून पुढे सुरू करा",
    continue: "सुरू ठेवा",
    finished: "पूर्ण झाले",
    cardDescription: "या मूल्यांकनावर आधारित तुमचे सविस्तर RIASEC विश्लेषण आणि करिअर शिफारसी पाहा.",
    returnToDashboard: "डॅशबोर्डवर परत जा",
    programs: "कार्यक्रम",
    careerDescription: "विविध शाखांमधील 88 शैक्षणिक कार्यक्रम आणि 21 करिअर मार्गांचा शोध घ्या.",
    notFoundDescription: "तुम्ही योग्य ठिकाणी आला आहात का?",
    previous: "मागील",
    nextQuestion: "पुढील प्रश्न",
    completeAssessment: "मूल्यांकन पूर्ण करा",
    noQuestionsFound2: "तुमच्या फिल्टरशी जुळणारे कोणतेही प्रश्न सापडले नाहीत.",
    CMsoon: "करिअर व्यवस्थापन UI लवकरच येत आहे...",
    UMsoon: "वापरकर्ता व्यवस्थापन UI लवकरच येत आहे...",
  },

  kn: {
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    careers: "ವೃತ್ತಿಗಳು",
    courses: "ಕೋರ್ಸ್‌ಗಳು",
    admin: "ಅಡ್ಮಿನ್",
    logout: "ಲಾಗ್ ಔಟ್",
    welcome: "ಮತ್ತೆ ಸುಸ್ವಾಗತ",
    startAssessment: "ಹೊಸ ಮೌಲ್ಯಮಾಪನವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    exploreCareers: "ವೃತ್ತಿ ಲೈಬ್ರರಿಯನ್ನು ಅನ್ವೇಷಿಸಿ",
    readyToExplore: "ನಿಮ್ಮ ಭವಿష్యತ್ತಿನ ವೃತ್ತಿ ಸಾಧ್ಯತೆಗಳನ್ನು ಅನ್వేಷಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    careerLibrary: "ವೃತ್ತಿ ಲೈಬ್ರರಿ",
    searchPlaceholder: "ವೃತ್ತಿಗಳು ಅಥವಾ ವಿವರಣೆಗಳನ್ನು ಹುಡುಕಿ...",
    allStreams: "ಎಲ್ಲಾ ಸ್ಟ್ರೀಮ್‌ಗಳು",
    assessmentResults: "ಮೌಲ್ಯಮಾపನ ಫಲಿತಾಂಶಗಳು",
    personalityProfile: "ನಿಮ್ಮ ವ್ಯಕ್ತಿತ್ವದ ಪ್ರೊಫೈಲ್",
    dominantTrait: "ಪ್ರధాన ಲಕ್ಷಣ",
    recommendedCareers: "ಶಿಫಾರಸು ಮಾಡಿದ ವೃತ್ತಿಗಳು",
    suggestedCourses: "ಸೂಚಿಸಲಾದ ಕೋರ್ಸ್‌ಗಳು",
    startLine: "ಇಂದೇ ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಆರಂಭಿಸಿ",
    startDescription: "ನಮ್ಮ ಸಮಗ್ರ RIASEC ಮೌಲ್ಯಮಾಪನವು ನಿಮ್ಮ ಆಸಕ್ತಿಗಳು ಮತ್ತು ಸಾಮರ್ಥ್ಯಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ, ನೀವು ಪ್ರೀತಿಸುವ ವೃತ್ತಿಗಳೊಂದಿಗೆ ನಿಮಗೆ ಹೊಂದಾಣಿಕೆ ಮಾಡುತ್ತದೆ. ಇದಕ್ಕೆ ಕೇವಲ ಸುಮಾರು 15 ನಿಮಿಷಗಳು ಮಾತ್ರ ಬೇಕಾಗುತ್ತವೆ!",
    takeAssessment: "ಮೌಲ್ಯಮಾಪನ ತೆಗೆದುಕೊಳ್ಳಿ",
    searchProgrammes: "ಕಾರ್ಯಕ್ರಮಗಳು ಅಥವಾ ಶಾಖೆಗಳನ್ನು ಹುಡುಕಿ...",
    searchCareers: "ವೃತ್ತಿಗಳನ್ನು ಹುಡುಕಿ...",
    searchQuestions: "ಪ್ರಶ್ನೆಗಳನ್ನು ಹುಡುಕಿ...",
    assessmentQuestions: "ಮೌಲ್ಯಮಾಪನ ಪ್ರಶ್ನೆಗಳು",
    manageItemsDescription: "ಮನೋವೈಜ್ಞಾನಿಕ ಪ್ರಶ್ನಾವಳಿ ಅಂಶಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    pleaseEnter: "ಸೈನ್ ಇನ್ ಮಾಡಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.",
    logoSheet1: "ನಿಮ್ಮ ಆದರ್ಶ ವೃತ್ತಿ ಮಾರ್ಗವನ್ನು ಅನ್ವೇಷಿಸಿ",
    logoSheet2: "ವೈಜ್ಞಾನಿಕವಾಗಿ ಮಾನ್ಯಗೊಂಡ ನಮ್ಮ RIASEC ಮೌಲ್ಯಮಾಪನವನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ ಮತ್ತು ನಿಮ್ಮ ಶಕ್ತಿಗಳು, ಆಸಕ್ತಿಗಳು ಹಾಗೂ ನಿಮಗಾಗಿ ಕಾಯುತ್ತಿರುವ ಸೂಕ್ತ ವೃತ್ತಿ ಅವಕಾಶಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    logoSheet3: "ತಮ್ಮ ಭವಿಷ್ಯವನ್ನು ಅನ್ವೇಷಿಸುತ್ತಿರುವ 10,000+ ವಿದ್ಯಾರ್ಥಿಗಳೊಂದಿಗೆ ಸೇರಿ",
    inProgress: "ಪ್ರಗತಿಯಲ್ಲಿದೆ",
    completedAssessments: "ಪೂರ್ಣಗೊಂಡ ಮೌಲ್ಯಮಾಪನಗಳು",
    assessment: "ಮೌಲ್ಯಮಾಪನ",
    completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    viewResults: "ಫಲಿತಾಂಶಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    noQuestionsFound1: "ಈ ಮೌಲ್ಯಮಾಪನಕ್ಕಾಗಿ ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    resultDescription1: "RIASEC ಮಾದರಿಯನ್ನು ಆಧರಿಸಿದ ನಿಮ್ಮ ವೈಯಕ್ತಿಕೃತ ವೃತ್ತಿ ಪ್ರೊಫೈಲ್",
    resultDescription2: "6 ಆಯಾಮಗಳಾದ್ಯಂತ ನಿಮ್ಮ ಆಸಕ್ತಿಗಳ ದೃಶ್ಯಾತ್ಮಕ ಪ್ರತಿನಿಧಿಕೆ",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    fullname: "ಪೂರ್ಣ ಹೆಸರು",
    username: "ಬಳಕೆದಾರ ಹೆಸರು",
    password: "ಪಾಸ್ವರ್ಡ್",
    confirm: "ದೃಢೀಕರಿಸಿ",
    fgPassword: "ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ",
    classLevel: "ತರಗತಿ ಮಟ್ಟ",
    stream: "ಸ್ಟ್ರೀಮ್",
    city: "ನಗರ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    signIn: "ಸೈನ್ ಇನ್",
    started: "ಪ್ರಾರಂಭಿಸಲಾಗಿದೆ",
    resume: "ನೀವು ನಿಲ್ಲಿಸಿದ ಸ್ಥಳದಿಂದ ಮುಂದುವರಿಸಿ",
    continue: "ಮುಂದುವರಿಸಿ",
    finished: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    cardDescription: "ಈ ಮೌಲ್ಯಮಾಪನದ ಆಧಾರದ ಮೇಲೆ ನಿಮ್ಮ ವಿವರವಾದ RIASEC ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ವೃತ್ತಿ ಶಿಫಾರಸುಗಳನ್ನು ನೋಡಿ.",
    returnToDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    programs: "ಕಾರ್ಯಕ್ರಮಗಳು",
    careerDescription: "ವಿವಿಧ ಸ್ಟ್ರೀಮ್‌ಗಳಲ್ಲಿ 88 ಶೈಕ್ಷಣಿಕ ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು 21 ವೃತ್ತಿ ಮಾರ್ಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    notFoundDescription: "ನೀವು ಸರಿಯಾದ ಸ್ಥಳಕ್ಕೆ ಬಂದಿದ್ದೀರಾ?",
    previous: "ಹಿಂದಿನ",
    nextQuestion: "ಮುಂದಿನ ಪ್ರಶ್ನೆ",
    completeAssessment: "ಮೌಲ್ಯಮಾಪನವನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ",
    noQuestionsFound2: "ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದುವ ಪ್ರಶ್ನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    CMsoon: "ವೃತ್ತಿ ನಿರ್ವಹಣಾ UI ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ...",
    UMsoon: "ಬಳಕೆದಾರ ನಿರ್ವಹಣಾ UI ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ...",
  },

  ml: {
    dashboard: "ഡാഷ്‌ബോർഡ്",
    careers: "കരിയറുകൾ",
    courses: "കോഴ്സുകൾ",
    admin: "അഡ്മിൻ",
    logout: "ലോഗൗട്ട്",
    welcome: "വീണ്ടും സ്വാഗതം",
    startAssessment: "പുതിയ വിലയിരുത്തൽ ആരംഭിക്കുക",
    exploreCareers: "കരിയർ ലൈബ്രറി പര്യവേക്ഷണം ചെയ്യുക",
    readyToExplore: "നിങ്ങളുടെ ഭാവി കരിയർ സാധ്യതകൾ പര്യവേക്ഷണം ചെയ്യാൻ തയ്യാറാണോ?",
    careerLibrary: "കരിയർ ലൈബ്രറി",
    searchPlaceholder: "കരിയറുകളോ വിവരണങ്ങളോ തിരയുക...",
    allStreams: "എല്ലാ സ്ട്രീമുകളും",
    assessmentResults: "വിലയിരുത്തൽ ഫലങ്ങൾ",
    personalityProfile: "നിങ്ങളുടെ വ്യക്തിത്വ പ്രൊഫൈൽ",
    dominantTrait: "പ്രധാന സ്വഭാവം",
    recommendedCareers: "ശുപാർശ ചെയ്യുന്ന കരിയറുകൾ",
    suggestedCourses: "നിർദ്ദേശിച്ച കോഴ്സുകൾ",
    startLine: "ഇന്നുതന്നെ നിങ്ങളുടെ യാത്ര ആരംഭിക്കൂ",
    startDescription: "ഞങ്ങളുടെ സമഗ്രമായ RIASEC മൂല്യനിർണയം നിങ്ങളുടെ താൽപര്യങ്ങളും കഴിവുകളും വിശകലനം ചെയ്ത് നിങ്ങൾക്ക് ഇഷ്ടപ്പെടുന്ന കരിയറുകളുമായി നിങ്ങളെ പൊരുത്തപ്പെടുത്തുന്നു. ഇതിന് ഏകദേശം 15 മിനിറ്റ് മാത്രമേ വേണ്ടൂ!",
    takeAssessment: "മൂല്യനിർണയം ആരംഭിക്കുക",
    searchProgrammes: "പ്രോഗ്രാമുകൾ അല്ലെങ്കിൽ ശാഖകൾ തിരയുക...",
    searchCareers: "കരിയറുകൾ തിരയുക...",
    searchQuestions: "ചോദ്യങ്ങൾ തിരയുക...",
    assessmentQuestions: "മൂല്യനിർണയ ചോദ്യങ്ങൾ",
    manageItemsDescription: "സൈക്കോമെട്രിക് ചോദ്യാവലിയുടെ ഘടകങ്ങൾ നിയന്ത്രിക്കുക.",
    pleaseEnter: "സൈൻ ഇൻ ചെയ്യുന്നതിനായി ദയവായി നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക.",
    logoSheet1: "നിങ്ങളുടെ അനുയോജ്യമായ കരിയർ പാത കണ്ടെത്തൂ",
    logoSheet2: "ശാസ്ത്രീയമായി സ്ഥിരീകരിച്ച ഞങ്ങളുടെ RIASEC മൂല്യനിർണയം സ്വീകരിച്ച് നിങ്ങളുടെ ശക്തികളും താൽപര്യങ്ങളും നിങ്ങളെ കാത്തിരിക്കുന്ന അനുയോജ്യമായ കരിയർ അവസരങ്ങളും കണ്ടെത്തൂ.",
    logoSheet3: "തങ്ങളുടെ ഭാവി കണ്ടെത്തുന്ന 10,000+ വിദ്യാർത്ഥികളോടൊപ്പം ചേരൂ",
    inProgress: "പുരോഗതിയിൽ",
    completedAssessments: "പൂർത്തിയായ മൂല്യനിർണയങ്ങൾ",
    assessment: "മൂല്യനിർണയം",
    completed: "പൂർത്തിയായി",
    viewResults: "ഫലങ്ങൾ കാണുക",
    noQuestionsFound1: "ഈ മൂല്യനിർണയത്തിനായി ചോദ്യങ്ങളൊന്നും കണ്ടെത്തിയില്ല.",
    resultDescription1: "RIASEC മാതൃകയെ അടിസ്ഥാനമാക്കിയുള്ള നിങ്ങളുടെ വ്യക്തിഗത കരിയർ പ്രൊഫൈൽ",
    resultDescription2: "6 അളവുകളിലുടനീളം നിങ്ങളുടെ താൽപര്യങ്ങളുടെ ദൃശ്യാവിഷ്കാരം",
    login: "ലോഗിൻ",
    register: "രജിസ്റ്റർ",
    fullname: "പൂർണ്ണ പേര്",
    username: "ഉപയോക്തൃനാമം",
    password: "പാസ്‌വേഡ്",
    confirm: "സ്ഥിരീകരിക്കുക",
    fgPassword: "പാസ്‌വേഡ് മറന്നോ",
    classLevel: "ക്ലാസ് നില",
    stream: "സ്ട്രീം",
    city: "നഗരം",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    signIn: "സൈൻ ഇൻ",
    started: "തുടങ്ങി",
    resume: "നിങ്ങൾ നിർത്തിയിടത്ത് നിന്ന് തുടരുമ്",
    continue: "തുടരുക",
    finished: "പൂർത്തിയായി",
    cardDescription: "ഈ മൂല്യനിർണ്ണയത്തെ അടിസ്ഥാനമാക്കി നിങ്ങളുടെ വിശദമായ RIASEC വിശകലനവും കരിയർ ശുപാർശകളും കാണുക.",
    returnToDashboard: "ഡാഷ്‌ബോർഡിലേക്ക് മടങ്ങുക",
    programs: "പ്രോഗ്രാമുകൾ",
    careerDescription: "വിവിധ സ്ട്രീമുകളിലായി 88 അക്കാദമിക് പ്രോഗ്രാമുകളും 21 കരിയർ വഴികളും അന്വേഷിക്കുക.",
    notFoundDescription: "നിങ്ങൾ ശരിയായ സ്ഥലത്താണോ?",
    previous: "മുൻപത്തെ",
    nextQuestion: "അടുത്ത ചോദ്യം",
    completeAssessment: "മൂല്യനിർണ്ണയം പൂർത്തിയാക്കുക",
    noQuestionsFound2: "നിങ്ങളുടെ ഫിൽട്ടറുകൾക്ക് പൊരുത്തപ്പെടുന്ന ചോദ്യങ്ങളൊന്നും കണ്ടെത്തിയില്ല.",
    CMsoon: "കരിയർ മാനേജ്മെന്റ് UI ഉടൻ വരുന്നു...",
    UMsoon: "യൂസർ മാനേജ്മെന്റ് UI ഉടൻ വരുന്നു...",
  },

  gu: {
    dashboard: "ડેશબોર્ડ",
    careers: "કરિયર",
    courses: "અભ્યાસક્રમો",
    admin: "એડમિન",
    logout: "લોગઆઉટ",
    welcome: "સ્વાગત છે",
    startAssessment: "નવું મૂલ્યાંકન શરૂ કરો",
    exploreCareers: "કરિયર લાઇબ્રેરી એક્સપ્લોર કરો",
    readyToExplore: "શું તમે તમારી ભવિષ્યની કરિયરની શક્યતાઓ શોધવા માટે તૈયાર છો?",
    careerLibrary: "કરિયર લાઇબ્રેરી",
    searchPlaceholder: "કરિયર અથવા વર્ણન શોધો...",
    allStreams: "બધી સ્ટ્રીમ્સ",
    assessmentResults: "મૂલ્યાંકન પરિણામો",
    personalityProfile: "તમારી વ્યક્તિત્વ પ્રોફાઇલ",
    dominantTrait: "મુખ્ય લક્ષણ",
    recommendedCareers: "ભલામણ કરેલ કરિયર",
    suggestedCourses: "સૂચવેલ અભ્યાસક્રમો",
    startLine: "આજથી તમારી યાત્રા શરૂ કરો",
    startDescription: "અમારું વ્યાપક RIASEC મૂલ્યાંકન તમારી રુચિઓ અને ક્ષમતાનું વિશ્લેષણ કરીને તમને તમને ગમતી કારકિર્દીઓ સાથે જોડે છે. તેમાં માત્ર અંદાજે 15 મિનિટ લાગે છે!",
    takeAssessment: "મૂલ્યાંકન લો",
    searchProgrammes: "પ્રોગ્રામ્સ અથવા શાખાઓ શોધો...",
    searchCareers: "કારકિર્દીઓ શોધો...",
    searchQuestions: "પ્રશ્નો શોધો...",
    assessmentQuestions: "મૂલ્યાંકન પ્રશ્નો",
    manageItemsDescription: "સાયકોમેટ્રિક પ્રશ્નાવલીના મુદ્દાઓ સંચાલિત કરો.",
    pleaseEnter: "સાઇન ઇન કરવા માટે કૃપા કરીને તમારી વિગતો દાખલ કરો.",
    logoSheet1: "તમારો આદર્શ કારકિર્દી માર્ગ શોધો",
    logoSheet2: "વિજ્ઞાન આધારિત અમારી RIASEC મૂલ્યાંકન પ્રક્રિયા દ્વારા તમારી શક્તિઓ, રુચિઓ અને તમને રાહ જોઈ રહેલી યોગ્ય કારકિર્દી તકો શોધો.",
    logoSheet3: "તેમનું ભવિષ્ય શોધતા 10,000+ વિદ્યાર્થીઓ સાથે જોડાઓ",
    inProgress: "પ્રગતિમાં",
    completedAssessments: "પૂર્ણ થયેલ મૂલ્યાંકનો",
    assessment: "મૂલ્યાંકન",
    completed: "પૂર્ણ",
    viewResults: "પરિણામો જુઓ",
    noQuestionsFound1: "આ મૂલ્યાંકન માટે કોઈ પ્રશ્નો મળ્યા નથી.",
    resultDescription1: "RIASEC મોડેલ આધારિત તમારી વ્યક્તિગત કારકિર્દી પ્રોફાઇલ",
    resultDescription2: "6 પરિમાણોમાં તમારી રુચિઓનું દૃશ્યાત્મક પ્રતિનિધિત્વ",
    login: "લોગિન",
    register: "નોંધણી",
    fullname: "પૂર્ણ નામ",
    username: "વપરાશકર્તા નામ",
    password: "પાસવર્ડ",
    confirm: "પુષ્ટિ કરો",
    fgPassword: "પાસવર્ડ ભૂલી ગયા છો",
    classLevel: "ધોરણ સ્તર",
    stream: "સ્ટ્રીમ",
    city: "શહેર",
    createAccount: "ખાતું બનાવો",
    signIn: "સાઇન ઇન",
    started: "શરૂ થયું",
    resume: "જ્યાં છોડ્યું ત્યાંથી ચાલુ કરો",
    continue: "ચાલુ રાખો",
    finished: "પૂર્ણ થયું",
    cardDescription: "આ મૂલ્યાંકનના આધારે તમારું વિગતવાર RIASEC વિશ્લેષણ અને કારકિર્દી ભલામણો જુઓ.",
    returnToDashboard: "ડેશબોર્ડ પર પાછા જાઓ",
    programs: "કાર્યક્રમો",
    careerDescription: "વિવિધ સ્ટ્રીમ્સમાં 88 શૈક્ષણિક કાર્યક્રમો અને 21 કારકિર્દી માર્ગો શોધો.",
    notFoundDescription: "શું તમે યોગ્ય જગ્યાએ આવ્યા છો?",
    previous: "પાછલું",
    nextQuestion: "આગળનો પ્રશ્ન",
    completeAssessment: "મૂલ્યાંકન પૂર્ણ કરો",
    noQuestionsFound2: "તમારા ફિલ્ટર સાથે મેળ ખાતા કોઈ પ્રશ્નો મળ્યા નથી.",
    CMsoon: "કારકિર્દી મેનેજમેન્ટ UI ટૂંક સમયમાં આવી રહ્યું છે...",
    UMsoon: "યુઝર મેનેજમેન્ટ UI ટૂંક સમયમાં આવી રહ્યું છે...",
  },

  ur: {
    dashboard: "ڈیش بورڈ",
    careers: "کیریئر",
    courses: "کورسز",
    admin: "ایڈمن",
    logout: "لاگ آؤٹ",
    welcome: "خوش آمدید",
    startAssessment: "نیا جائزہ شروع کریں",
    exploreCareers: "کیریئر لائبریری دریافت کریں",
    readyToExplore: "کیا آپ اپنے مستقبل کے کیریئر کے امکانات تلاش کرنے کے لیے تیار ہیں؟",
    careerLibrary: "کیریئر لائبریری",
    searchPlaceholder: "کیریئر یا تفصیلات تلاش کریں...",
    allStreams: "تمام شعبے",
    assessmentResults: "جائزے کے نتائج",
    personalityProfile: "آپ کی شخصیت کا پروفائل",
    dominantTrait: "غالب صفت",
    recommendedCareers: "تجویز کردہ کیریئر",
    suggestedCourses: "تجویز کردہ کورسز",
    startLine: "آج ہی اپنا سفر شروع کریں",
    startDescription: "ہماری جامع RIASEC تشخیص آپ کی دلچسپیوں اور صلاحیتوں کا تجزیہ کر کے آپ کو اُن کیریئرز سے ہم آہنگ کرتی ہے جو آپ کو پسند آئیں۔ اس میں صرف تقریباً 15 منٹ لگتے ہیں!",
    takeAssessment: "تشخیص شروع کریں",
    searchProgrammes: "پروگرامز یا شعبے تلاش کریں...",
    searchCareers: "کیریئرز تلاش کریں...",
    searchQuestions: "سوالات تلاش کریں...",
    assessmentQuestions: "تشخیصی سوالات",
    manageItemsDescription: "سائیکومیٹرک سوالنامے کے آئٹمز کو منظم کریں۔",
    pleaseEnter: "سائن اِن کرنے کے لیے براہِ کرم اپنی تفصیلات درج کریں۔",
    logoSheet1: "اپنا مثالی کیریئر راستہ دریافت کریں",
    logoSheet2: "سائنسی بنیادوں پر تیار کردہ ہماری RIASEC تشخیص کے ذریعے اپنی صلاحیتیں، دلچسپیاں اور آپ کے لیے موجود بہترین کیریئر مواقع دریافت کریں۔",
    logoSheet3: "اپنا مستقبل دریافت کرنے والے 10,000+ طلبہ میں شامل ہوں",
    inProgress: "جاری ہے",
    completedAssessments: "مکمل شدہ تشخیصات",
    assessment: "تشخیص",
    completed: "مکمل",
    viewResults: "نتائج دیکھیں",
    noQuestionsFound1: "اس تشخیص کے لیے کوئی سوالات نہیں ملے۔",
    resultDescription1: "RIASEC ماڈل کی بنیاد پر آپ کا ذاتی نوعیت کا کیریئر پروفائل",
    resultDescription2: "6 جہتوں میں آپ کی دلچسپیوں کی بصری نمائندگی",
    login: "لاگ اِن",
    register: "رجسٹر",
    fullname: "پورا نام",
    username: "صارف نام",
    password: "پاس ورڈ",
    confirm: "تصدیق کریں",
    fgPassword: "پاس ورڈ بھول گئے",
    classLevel: "جماعت کی سطح",
    stream: "اسٹریم",
    city: "شہر",
    createAccount: "اکاؤنٹ بنائیں",
    signIn: "سائن اِن",
    started: "شروع کیا گیا",
    resume: "جہاں چھوڑا تھا وہیں سے دوبارہ شروع کریں",
    continue: "جاری رکھیں",
    finished: "مکمل",
    cardDescription: "اس تشخیص کی بنیاد پر اپنی تفصیلی RIASEC تجزیہ اور کیریئر سفارشات دیکھیں۔",
    returnToDashboard: "ڈیش بورڈ پر واپس جائیں",
    programs: "پروگرامز",
    careerDescription: "مختلف اسٹریمز میں 88 تعلیمی پروگرامز اور 21 کیریئر راستوں کو دریافت کریں۔",
    notFoundDescription: "کیا آپ صحیح جگہ پر آئے ہیں؟",
    previous: "پچھلا",
    nextQuestion: "اگلا سوال",
    completeAssessment: "تشخیص مکمل کریں",
    noQuestionsFound2: "آپ کے فلٹرز سے مطابقت رکھنے والے کوئی سوالات نہیں ملے۔",
    CMsoon: "کیریئر مینجمنٹ UI جلد آ رہا ہے...",
    UMsoon: "یوزر مینجمنٹ UI جلد آ رہا ہے...",
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const STORAGE_KEY = "career-path-lang";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem(STORAGE_KEY) as Language) || "en";
  });

  const t = (key: keyof typeof translations.en) => {
    return (translations[language] as any)?.[key] || translations.en[key];
  };

  const handleSetLanguage = (lang: Language) => {
    localStorage.setItem(STORAGE_KEY, lang);
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage: handleSetLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context)
    throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
